### ISSUE TITLE
not working the latest codigniter 4

### ISSUE THREAD

**Issue by pioneersingh321** [FoLez/slice-ci4#1]
its throwing error not working in latest codigniter 4

**Comment by FoLez** [comment]
Hello, show error log please

**Comment by AndreyDemenenko** [comment]
> its throwing error not working in latest codigniter 4

Show error log

**Comment by pioneersingh321** [comment]
ErrorException
Undefined index: memberData
APPPATH\Libraries\Slice.php at line 169

**Comment by pioneersingh321** [comment]
CRITICAL - 2021-05-02 04:40:16 --> Undefined index: memberData
#0 D:\mamp_htdoc\bitbucket\hotelcrm_ci4\app\Libraries\Slice.php(169): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'D:\\mamp_htdoc\\b...', 169, Array)
#1 D:\mamp_htdoc\bitbucket\hotelcrm_ci4\app\Controllers\Webpanel\Webpanel.php(59): App\Libraries\Slice->__construct()
#2 D:\mamp_htdoc\bitbucket\hotelcrm_ci4\system\CodeIgniter.php(909): App\Controllers\Webpanel\Webpanel->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#3 D:\mamp_htdoc\bitbucket\hotelcrm_ci4\system\CodeIgniter.php(422): CodeIgniter\CodeIgniter->createController()
#4 D:\mamp_htdoc\bitbucket\hotelcrm_ci4\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\mamp_htdoc\bitbucket\hotelcrm_ci4\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}

**Comment by pioneersingh321** [comment]
CRITICAL - 2021-05-02 04:40:16 --> Undefined index: memberData

**Comment by pioneersingh321** [comment]
i think this function 
$this->CI->output->append_output($content);  
at line 359 will also not work ...
